apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: webapp
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: registry.ngaxavilabs.com/devops/webapp
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          TARGET: dev
        cacheFrom:
          - registry.ngaxavilabs.com/devops/webapp:latest
deploy:
  kubectl:
    manifests:
      - k8s/dev-deployment.yaml

profiles:
  - name: dev
    patches:
      - op: add
        path: /build/tagPolicy/gitCommit/prefix
        value: dev-
    deploy:
      kubectl:
        manifests:
          - k8s/dev-deployment.yaml
        flags:
          disableValidation: false
  - name: production
    patches:
      - op: replace
        path: /build/artifacts/0/docker/buildArgs/TARGET
        value: prod
      - op: replace
        path: /build/tagPolicy/gitCommit/variant
        value: Tags
    deploy:
      kubectl:
        manifests:
          - k8s/production-deployment.yaml
        flags:
          disableValidation: false
  - name: staging
    patches:
      - op: replace
        path: /build/artifacts/0/docker/buildArgs/TARGET
        value: staging
      - op: add
        path: /build/tagPolicy/gitCommit/prefix
        value: staging-
    deploy:
      kubectl:
        manifests:
          - k8s/staging-deployment.yaml
        flags:
          disableValidation: false
